name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run tests
        run: ./gradlew test

      - name: Dependency Check Purge
        run: ./gradlew dependencyCheckPurge

      - name: Dependency Check Analyze
        run: ./gradlew dependencyCheckAnalyze

      - name: Clean workspace
        if: always()
        run: rm -rf ${{ github.workspace }}

      - name: Success message
        if: success()
        run: echo 'Build and deployment successful!'

      - name: Failure message
        if: failure()
        run: echo 'Build or deployment failed.'